### ISSUE TITLE
[WinError 3] 系统找不到指定的路径。: 'D:\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-InstantMesh'

### ISSUE THREAD

**Issue by laidingq** [jtydhr88/ComfyUI-InstantMesh#1]
Error occurred when executing InstantMeshLoader:

[WinError 3] 系统找不到指定的路径。: 'D:\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-InstantMesh'

File "D:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 335, in run
model,config = load_InstantMeshModel(config_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-InstantMesh\run.py", line 88, in load_InstantMeshModel
os.chdir(target_directory)

**Comment by jtydhr88** [comment]
Hi, 我在里面有一段是靠配接字符串找的路径，你在那变成了D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantMesh'，看起来D:\ComfyUI是你的根目录吧？
我用的目录结构是comfyui解包后默认的路径

**Comment by laidingq** [comment]
我的目录是D:\ComfyUI\custom_nodes\ComfyUI-InstantMesh这样的，但在运行的时候多了 一层comfyui

**Comment by laidingq** [comment]
py311  torch2.1.2 +cu121   miniconda
环境应该没啥问题，我每天装新出来的各种插件

**Comment by jtydhr88** [comment]
啊我是想确认一下python的路径在哪里…我做的时候只考虑了comfyui默认的那种解压缩之后的文件夹结构。我这周有时间的时候想想该怎么解决这种情况哈，感谢反馈！

**Comment by laidingq** [comment]
3Q

**Comment by akspa0** [comment]
I patched run.py with forward slashes and changing the path to the extension from "ComfyUI\custom_nodes\ComfyUI-InstantMesh" to "custom_nodes/ComfyUI-InstantMesh", and now the downloading of models appears to work properly and the extension appears to work properly on a Linux install of ComfyUI (I say 'appears', because I ran out of VRAM on my old GPU, but it got far enough into the process that I'm quite certain it's working properly!).

**Comment by jtydhr88** [comment]
@akspa0 thanks to verify, yes, the solution for this problem is quite simple, just change the path in my code, I am considering how to handle the general case

**Comment by jtydhr88** [comment]
hi, I tried to fix this issue in latest commit 6bc7ed08eba9ce52510f4538e273a9575fd16c65, please let me know it works or not
