### ISSUE TITLE
Two steps process 

### ISSUE THREAD

**Issue by Abocg** [jtydhr88/ComfyUI-InstantMesh#10]
Hi. Thanks for your implementation. I just wanted to ask if possible to make it two steps process so that I can refine the generated multiview image in stable diffusion and give it more details and feed it back to the 3D processer just like CRM code in Mr.forexample 3D pack. Many thanks in advance

**Comment by jtydhr88** [comment]
hi @Abocg, in fact InstantMesh has plan to support different Diffusion model, see 
![image](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/860985/8339c38a-1791-4a36-9eb4-b011ca6d2245)
https://github.com/TencentARC/InstantMesh
So once they complete, I will implement this comfyUI custom nodes here.
Please keey an eye on it. I will close this issue for now.
