### ISSUE TITLE
Does it make sense to allow more than six views??

### ISSUE THREAD

**Issue by webcoderz** [jtydhr88/ComfyUI-InstantMesh#13]
Does it make sense to allow more than six views??

**Comment by jtydhr88** [comment]
No, this is because InstantMesh self implementation, , it only allows up to 6.
Please refer to its official paper

**Comment by jtydhr88** [comment]
See:
![IMG_1588](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/860985/209c1d23-5074-463a-878c-20f64cf0cf4f)

**Comment by webcoderz** [comment]
Ahh nice. Thx
