### ISSUE TITLE
win11  RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by guahunyo** [jtydhr88/ComfyUI-InstantMesh#2]

**Comment by jtydhr88** [comment]
hi, please follow the install steps:
First, this extension depends on [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack), please install it if not, and make sure it works well:

stop ComfyUI if it is running
goto ComfyUI/custom_nodes dir in terminal(cmd)
git clone https://github.com/MrForExample/ComfyUI-3D-Pack
cd ComfyUI-3D-Pack
run install_windows_portable_win_py311_cu121.bat
(Don't start ComfyUI at this moment)
Then, install this extension:

git clone https://github.com/jtydhr88/ComfyUI-InstantMesh
cd ComfyUI-InstantMesh
run install_windows_portable_win_py311_cu121.bat
Start your ComfyUI.

**Comment by guahunyo** [comment]
![86X}$2W%$GHA$M3P)(S`6NN](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/18573180/69da13e3-80c2-4b86-976c-99ec9efc07f0)
这样就好了

**Comment by guahunyo** [comment]
> hi, please follow the install steps: First, this extension depends on [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack), please install it if not, and make sure it works well:
> 
> stop ComfyUI if it is running goto ComfyUI/custom_nodes dir in terminal(cmd) git clone https://github.com/MrForExample/ComfyUI-3D-Pack cd ComfyUI-3D-Pack run install_windows_portable_win_py311_cu121.bat (Don't start ComfyUI at this moment) Then, install this extension:
> 
> git clone https://github.com/jtydhr88/ComfyUI-InstantMesh cd ComfyUI-InstantMesh run install_windows_portable_win_py311_cu121.bat Start your ComfyUI.

跟这个没关系

**Comment by jtydhr88** [comment]
ok

**Comment by guahunyo** [comment]
> ok

![image](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/18573180/097c98bc-678f-4e21-a5d5-1a83a3407273)
然后现在是这个报错

**Comment by guahunyo** [comment]
> hi, please follow the install steps: First, this extension depends on [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack), please install it if not, and make sure it works well:
> 
> stop ComfyUI if it is running goto ComfyUI/custom_nodes dir in terminal(cmd) git clone https://github.com/MrForExample/ComfyUI-3D-Pack cd ComfyUI-3D-Pack run install_windows_portable_win_py311_cu121.bat (Don't start ComfyUI at this moment) Then, install this extension:
> 
> git clone https://github.com/jtydhr88/ComfyUI-InstantMesh cd ComfyUI-InstantMesh run install_windows_portable_win_py311_cu121.bat Start your ComfyUI.

我是完全照着这个来的

**Comment by guahunyo** [comment]
![image](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/18573180/1eb5b299-4a79-488f-9602-0def70a2e393)

**Comment by jtydhr88** [comment]
hello，确认一下，本地安装[Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=build+tools)这个工具了吗
![image](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/860985/6ff4a7c2-b3bc-46c6-8cde-c4fd9cc00516)?
我在InstantMesh本身的库里建了个ticket也提到这个了https://github.com/TencentARC/InstantMesh/issues/3

**Comment by jtydhr88** [comment]
请参考https://github.com/jtydhr88/ComfyUI-InstantMesh/issues/6

**Comment by ZZXYWQ** [comment]
> ![86X}$2W%$GHA$M3P)(S`6NN](https://private-user-images.githubusercontent.com/18573180/322696970-69da13e3-80c2-4b86-976c-99ec9efc07f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzQwNzksIm5iZiI6MTcxNTkzMzc3OSwicGF0aCI6Ii8xODU3MzE4MC8zMjI2OTY5NzAtNjlkYTEzZTMtODBjMi00Yjg2LTk3NmMtOTllYzllZmMwN2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA4MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMzQ0NzM0NWFiNzg1M2MwZGRmMDZkMzRiZDY1NGE4OTAwYjAzZTM0YTA1ZTdkM2VhMWY2ZGE3ZjBjYjU2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UCvNgauJWwe1TwAJpxidlMIkl897B8EOl8cCktDT77c) 这样就好了

对我不管用，我不知道为什么（哭）
