### ISSUE TITLE
 torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by Simsk8er** [jtydhr88/ComfyUI-InstantMesh#8]
I'm getting this error when I try to run.  

![Screenshot 2024-04-17 155622](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/120066157/58e20dbb-4a1e-4b4b-abf4-705ab23b4333)
![Screenshot 2024-04-17 155634](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/120066157/25f102b0-9b6d-4a8c-aeb2-7d780f9b7944)

**Comment by jtydhr88** [comment]
From log, it requests more VRAM , which could not be fixed here - ComfyUI custom node.
In fact, InstantMesh has plan to support low vram env, but not finish at this moment, see 
![image](https://github.com/jtydhr88/ComfyUI-InstantMesh/assets/860985/087327e5-aadf-44cb-95c2-04ca87e5acc6)
https://github.com/TencentARC/InstantMesh,
Please keek an eye on its process, 
I would close this issue
